name: Format check

on: workflow_call

jobs:
  format-check:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: node:${{vars.NODE_VERSION}}-alpine
    steps:
      - name: Install git
        run: apk add git
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run prettier check
        continue-on-error: true
        run: sh .github/scripts/prettier.sh
      - uses: actions/github-script@v6
        if: env.STATUS_CODE == 1
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Looks like you forgot to run Prettier. Hopefully you can automatically fix it by typing `/prettify` command.'
            })
      - name: Exit with prettier status code
        run: exit $STATUS_CODE
