name: Format

on:
  pull_request_review:
    types: [submitted]

jobs:
  format:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: node:${{vars.NODE_VERSION}}-alpine
    env:
      GH_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - name: Install git
        run: apk add git
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run prettier
        run: npm run prettify
      - name: Commit and push changes
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name reatom-bot
          git config --global user.email raman.aktsisiuk@gmail.com
          git commit -am "chore: run prettier"
          git push https://github.com/${{ github.repository }}.git HEAD:${{ github.event.pull_request.head.ref }}
