name: Format check

on:
  workflow_call:
    secrets:
      BOT_TOKEN:
        required: true

jobs:
  format-check:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: node:${{vars.NODE_VERSION}}-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run prettier check
        continue-on-error: true
        run: sh .github/scripts/prettier.sh
      - name: Create action comment
        if: env.STATUS_CODE == 1
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Looks like you forgot to run Prettier. Hopefully you can automatically fix it by typing `/prettify` command.'
            })
      - name: Exit with prettier status code
        run: exit $STATUS_CODE
