name: preview

on:
  pull_request:
    branches: [v3]

jobs:
  lint:
    uses: ./.github/workflows/format-check.yml
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  test:
    uses: ./.github/workflows/test.yml
