name: Test

on: workflow_call

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: node:22.13.1-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run tests
        run: npm test
